### ISSUE TITLE
[Enhancement] Show chatters name in chat log

### ISSUE THREAD

**Issue by PeterTaylorTX** [Djmater/TwitchBot#8]
Currently the chat messages are shown in the console, however the messages have the chatters numerical UID added to the end of the message.
It would be better to see the chatters username prefixed to the messages

i.e.
`petertaylortx: omg did you see that amazing thing`
`djmater: Yes, best thing ever`
`petertaylortx: Do you think Crumble will ever find that pizza again?`
`djmater: No, b/c I ate it`
`dj_crumble21: I hate you both`

**Comment by Djmater** [comment]
Fixed issue with latest commit 45d665e
